# Linear Algebra

**Overview**
This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [60]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 


**Hint**
The question relates to the limitations of floating point numbers.


---

In [55]:
# Write your solution here

A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)

print (A@A_inv)
print (np.identity(A.shape[0]))

h = (A @ A_inv == np.identity(A.shape[0]))
j = (C @ C_inv == np.identity(C.shape[0]))
print(h)
print(j)

# This works better because it approximate the floats to 0 or to 1:
h = np.allclose(A @ A_inv, np.identity(A.shape[0]))
j = np.allclose(C @ C_inv, np.identity(C.shape[0]))
print(h)
print(j)

[[ 1.00000000e+00  0.00000000e+00  2.27373675e-13  0.00000000e+00]
 [-1.55431223e-15  1.00000000e+00  1.12532206e-13  3.10862447e-14]
 [ 1.29526020e-15 -3.44909286e-14  1.00000000e+00 -4.48530102e-14]
 [-5.99520433e-15  8.00629404e-14 -1.61585031e-13  1.00000000e+00]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[False  True False  True]
 [False False False False]
 [False False False False]
 [False False False False]]
[[False False  True False]
 [False False False False]
 [False False False False]
 [False False False False]]
True
True


## Properties

---
**Task 2 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---

In [56]:
# Write your solution here

D_inv @ E_inv == np.linalg.inv(E @ D)
x = np.allclose(D_inv @ E_inv,np.linalg.inv(E @ D))
print(x)

# it is true the first statement

True



---
**Task 3 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---

In [61]:
# Write your solution here
A_det = np.linalg.det(A)
B_det = np.linalg.det(B)
C_det = np.linalg.det(C)
print(B)
print(B_det)
print(A_det,B_det,C_det)
# matrices A and C have an inverse because the determinant is not 0

#A_inv = np.linalg.inv(A)
#B_inv = np.linalg.inv(B)
#C_inv = np.linalg.inv(C)

[[-16  15 -14  13]
 [-12  11 -10   9]
 [ -8   7  -6   5]
 [ -4   3  -2   1]]
0.0
1.6534391534390412e-07 0.0 1.0498026371034301e-07



---
**Task 4 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.


---

In [51]:
# Write your solution here

D_inv.T 
x = np.allclose(D_inv.T ,np.linalg.inv(D.T))

print(x) # It is true the statement

True


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 5 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$

---

In [62]:
# Write your solutions here
# a)

A = np.array([[2, 3], [1, 1]])
b = np.array([-1,0])
det = np.linalg.det(A)
x = np.linalg.inv(A) @ b 
print("a) (x,y) =", x)

# b)

A = np.array([[1, 0], [0, 1]])
b = np.array([5,7])
det = np.linalg.det(A)
x = np.linalg.inv(A) @ b 
print("b) (x,y) =", x)

# c) 

A = np.array([[0, 1], [-2, -3]])
b = np.array([-1,2])
det = np.linalg.det(A)
x = np.linalg.inv(A) @ b 
print("c) (x,y) =", x)

# d) 

A = np.array([[1,-3,3], [1,-5,3], [6,-6,4]])
b = np.array([0.5,0.5,1])
det = np.linalg.det(A)
x = np.linalg.inv(A) @ b 
print("d) (x,y) =", x)

# e) 

A = np.array([[2,3,4], [1,4,1], [4,5,2]])
b = np.array([2,-2,3])
det = np.linalg.det(A)
x = np.linalg.inv(A) @ b 
print("e) (x,y) =", x)

# f) 

A = np.array([[1,1,1], [2,2,2], [3,3,3]])
b = np.array([2,-2,3])
det = np.linalg.det(A)
#x = np.linalg.inv(A) @ b 
print("f) det(A) = 0 so its not possible to solve the equation")

a) (x,y) = [ 1. -1.]
b) (x,y) = [5. 7.]
c) (x,y) = [ 0.5 -1. ]
d) (x,y) = [7.14285714e-02 5.55111512e-17 1.42857143e-01]
e) (x,y) = [ 1.90625 -1.0625   0.34375]
f) det(A) = 0 so its not possible to solve the equation


## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 6 (medium): Implementing matrix multiplication👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.


---

In [76]:
import numpy as np

def matmul(ma, mb):

    ma = ma.tolist()
    mb = mb.T.tolist()
    res = []
    for i in range(len(ma)):
        row = []
        for j in range(len(mb)):
            x = np.dot(ma[i], mb[j])
            row.append(x)
        res.append(row)
    print (np.array(res))


ma = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

mb = np.array([
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
])

matmul(ma, mb)


[[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]



---
**Task 7 (easy): Extra exercises💡**
Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)



---